force-app/main/default/objects/CareBenefitVerifyRequest/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <formula>MemberPlan.Member.PersonContact.Birthdate</formula>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CareBenefitVerifyRequest/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <formula>TEXT( MemberPlan.Member.PersonContact.Gender )</formula>
    <label>Gender</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareBenefitVerifyRequest/fields/National_Provider_Identifier__c.field-meta.xml
<CustomField>
    <fullName>National_Provider_Identifier__c</fullName>
    <formula>MemberPlan.Payer.National_Provider_Identifier_NPI__c</formula>
    <label>National Provider Identifier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MemberPlan/fields/Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>Subscriber_ID__c</fullName>
    <label>Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Detail__c/Service_Detail__c.object-meta.xml
<CustomObject>
    <label>Service Detail</label>
    <nameField>
        <displayFormat>SD-{00000}</displayFormat>
        <label>Service Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Detail__c/fields/Care_Benefit_Verify_Request__c.field-meta.xml
<CustomField>
    <fullName>Care_Benefit_Verify_Request__c</fullName>
    <label>Care Benefit Verify Request</label>
    <referenceTo>CareBenefitVerifyRequest</referenceTo>
    <relationshipLabel>Service Details</relationshipLabel>
    <relationshipName>Service_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Detail__c/fields/Diagnosis_Code__c.field-meta.xml
<CustomField>
    <fullName>Diagnosis_Code__c</fullName>
    <label>Diagnosis Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ICD-10</fullName>
            </value>
            <value>
                <fullName>ICD-11</fullName>
            </value>
            <value>
                <fullName>ICD-12</fullName>
            </value>
            <value>
                <fullName>ICD-13</fullName>
            </value>
            <value>
                <fullName>ICD-14</fullName>
            </value>
            <value>
                <fullName>ICD-15</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Detail__c/fields/Procedure_Code__c.field-meta.xml
<CustomField>
    <fullName>Procedure_Code__c</fullName>
    <label>Procedure Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>OPT</fullName>
            </value>
            <value>
                <fullName>DPT</fullName>
            </value>
            <value>
                <fullName>ONT</fullName>
            </value>
            <value>
                <fullName>UPT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Detail__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultation</fullName>
            </value>
            <value>
                <fullName>Infusion</fullName>
            </value>
            <value>
                <fullName>Surgery</fullName>
            </value>
            <value>
                <fullName>Lab Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CareBenefitCallout.cls
//queable method for async and higher limits
public with sharing class CareBenefitCallout implements Queueable, Database.AllowsCallouts {

    private Integer maxRetries = 3;
    private List<CareBenefitVerifyRequest> cbvRecordIds;

    public CareBenefitCallout(List<CareBenefitVerifyRequest> cbvRecordIds) {
        this.cbvRecordIds = cbvRecordIds;
    }

    public void execute(QueueableContext context) 
    {
        //Get care beneft verify records in bulk for processing and an inner query for service details
        List<CareBenefitVerifyRequest> records = [
            SELECT Id, Requester.FirstName, Requester.LastName,Birthdate__c,Gender__c , MemberPlan.Name, MemberPlan.MemberNumber, 
            MemberPlan.GroupNumber, MemberPlan.Subscriber_ID__c, 
            Provider.FirstName, Provider.LastName, National_Provider_Identifier__c, 
            (Select Id, Service_Date__c, Name, Service_Type__c, Procedure_Code__c, Diagnosis_Code__c from Service_Details__r LIMIT 1) 
            FROM CareBenefitVerifyRequest where Id IN :cbvRecordIds
        ];

        system.debug(records);


         List<CareBenefitVerifyWrapper.RequestWrapper> payload = new List<CareBenefitVerifyWrapper.RequestWrapper>();

         //loop to build payload
        for (CareBenefitVerifyRequest rec : records) {
            //Request wrapper class to build payload
            CareBenefitVerifyWrapper.RequestWrapper req = new CareBenefitVerifyWrapper.RequestWrapper();

            req.patientFirstName = rec.Requester.FirstName;
            req.patientLastName = rec.Requester.LastName;
            req.patientDOB = rec.Birthdate__c;
            req.patientGender = rec.Gender__c;

            req.insuranceProviderName = rec.MemberPlan.Name;
            req.policyNumber = rec.MemberPlan.MemberNumber;
            req.groupNumber = rec.MemberPlan.GroupNumber;
            req.subscriberId = rec.MemberPlan.Subscriber_ID__c;

            req.providerNPI = rec.National_Provider_Identifier__c;
            req.providerFirstName = rec.Provider.FirstName;
            req.providerLastName = rec.Provider.LastName;
            
            //System.debug(req.Service_Detail__c);

            Service_Detail__c detail = rec.Service_Details__r[0];
            req.serviceType = detail.Service_Type__c;
            req.serviceDate = detail.Service_Date__c;
            req.diagnosisCode = detail.Procedure_Code__c;
            req.procedureCode = detail.Diagnosis_Code__c;

            system.debug(req);

            payload.add(req);
        }
        //send reqyest method
        sendRequest(JSON.serialize(payload));
    }

    private void sendRequest(String jsonPayload) {
        
        Integer attempt = 0;
        Boolean success = false;
        
        List<CareBenefitVerifyRequest> records = [
            SELECT Id, Requester.FirstName, Requester.LastName,Birthdate__c,Gender__c , MemberPlan.Name, MemberPlan.MemberNumber, 
            MemberPlan.GroupNumber, MemberPlan.Subscriber_ID__c, 
            Provider.Name, Provider.LastName, National_Provider_Identifier__c, 
            (Select Id, Service_Date__c, Name, Service_Type__c, Procedure_Code__c, Diagnosis_Code__c from Service_Details__r LIMIT 1) 
            FROM CareBenefitVerifyRequest where Id IN :cbvRecordIds
        ];

        //http request to send send payload with retry mechanism 
        while (attempt < maxRetries && !success) {
            attempt++;
            try {
                HttpRequest req = new HttpRequest();
                req.setEndpoint('callout:ExternalBenefitVerification/benefit-verification-request');
                req.setMethod('POST');
                req.setHeader('Content-Type', 'application/json');
                req.setBody(jsonPayload);

                Http http = new Http();
                HttpResponse res = http.send(req);

                //handle status code errors
                if (res.getStatusCode() >= 200 && res.getStatusCode() < 300) {
                    success = true;
                    System.debug('Callout succeeded on attempt ' + attempt);
                    System.debug(JSON.deserializeUntyped(res.getBody()));
                    
                    String responseBody = res.getBody();

                    // Parse the JSON into a Map
                    Map<String, Object> parsedResponse = (Map<String, Object>) JSON.deserializeUntyped(responseBody);

                    String status = (String) parsedResponse.get('status');
                    String statusReason = (String) parsedResponse.get('statusReason');

                    //update records
                    if(status == 'Acknowledged')
                    {
                        for (CareBenefitVerifyRequest rec : records) {
                            rec.Status = 'Acknowledged';
                            rec.StatusReason = statusReason;
                        }
                        update records;
                    }

                } else {
                    System.debug('Callout attempt ' + attempt + ' failed with status: ' + res.getStatusCode());
                }
            }
            //handle all exceptions
            catch(Exception e){
                 System.debug('Callout attempt ' + attempt + ' threw exception: ' + e.getMessage());
            }

        }
    
    }
}